config/routes.rb
Rails.application.routes.draw do
  
  resources :grads
  resources :grad_courses, only: [:edit]
  resources :courses
  resources :schools
  post 'grad_courses/:id', to: 'grad_courses#update'
  get 'pages/home', to: 'pages#home'
  root 'pages#home'

end

app/models/grad.rb
class Grad < ActiveRecord::Base
    belongs_to :school
    has_many :grad_courses
    has_many :courses, through: :grad_courses
    accepts_nested_attributes_for :grad_courses,
    allow_destroy: true
    accepts_nested_attributes_for :courses,
    allow_destroy: true
end

app/controllers/grads_controller.rb
class GradsController < ApplicationController
  before_action :set_grad, only: [:show, :edit, :update, :destroy]

  # GET /grads
  # GET /grads.json
  def index
    @grads = Grad.all
  end

  # GET /grads/1
  # GET /grads/1.json
  def show
  end

  # GET /grads/new
  def new
    @grad = Grad.new
  end

  # GET /grads/1/edit
  def edit
  end

  # POST /grads
  # POST /grads.json
  def create
    @grad = Grad.new(grad_params)

    respond_to do |format|
      if @grad.save
        format.html { redirect_to @grad, notice: 'Grad was successfully created.' }
        format.json { render :show, status: :created, location: @grad }
      else
        format.html { render :new }
        format.json { render json: @grad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grads/1
  # PATCH/PUT /grads/1.json
  def update
    respond_to do |format|
      if @grad.update(grad_params)
        format.html { redirect_to edit_grad_course_path(@grad.id), notice: 'Grad was successfully updated.' }
        format.json { render :show, status: :ok, location: @grad }
      else
        format.html { render :edit }
        format.json { render json: @grad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grads/1
  # DELETE /grads/1.json
  def destroy
    @grad.destroy
    respond_to do |format|
      format.html { redirect_to grads_url, notice: 'Grad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grad
      @grad = Grad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grad_params
      params.require(:grad).permit(:name, :min, :max, :school_id, course_ids: [], grad_courses_attributes: [:id, :course_id, :grad_id, :semester ])
    end

end

app/views/grads/_form.html.erb
<div class="container well">
  <%= form_for @grad, html: {class: "form-horizontal"} do |f| %>
    <% if @grad.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@grad.errors.count, "error") %> prohibited this grad from being saved:</h2>
  
        <ul>
        <% @grad.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :Escola, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :school_id, School.all, :id, :name, {:prompt => ' '}, {:class=>'form-control'} %>

      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :Nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :"Semestres", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :max, class: "form-control" %>
      </div>
    </div>
    <div class="actions">
      <div class="form-group">
        <%= f.submit :Salvar, class: "btn btn-default col-sm-2 col-sm-offset-9" %>
      </div>
      
    </div>
  <% end %>
</div>

app/views/grads/_grad.html.erb
<%= link_to grad.name, grad_path(grad), class: "label label-info" %>

app/views/grads/edit.html.erb
<h1>Editar Graduação</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @grad %> |
<%= link_to 'Voltar', grads_path %>

app/views/grads/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Lista de Currículos</h1>

<div class="container well">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Escola</th>
        <th>Semestres</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @grads.each do |grad| %>
        <tr>
          <td>
            <%= link_to "#{grad.name}", grad %>
          </td>      
          <td>
            <%= link_to "#{grad.school.name}", school_path(grad.school_id) %>
          </td>  
          <td>
            <%= grad.max %>
          </td>
          <td>
            <%= link_to 'Editar Semestres', edit_grad_course_path(grad), type: "button", class: "label label-success" %>
            <%= link_to 'Editar', edit_grad_path(grad), type: "button", class: "label label-primary" %>
            <%= link_to 'Deletar', grad, type: "button", class: "label label-danger", method: :delete, data: { confirm: 'Tem certeza?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Novo Currículo', new_grad_path, type: "button", class: "btn btn-success btn-sm"  %>

app/views/grads/new.html.erb
<div class="text-center">
    <h1>Nova Graduação</h1>
</div>  

<%= render 'form' %>

<%= link_to 'Voltar', grads_path %>

app/views/grads/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @grad.name %></h1>
<div class="container well">
  <h4><%= link_to "#{@grad.school.name}", school_path(@grad.school_id) %></h4>
  <% if @grad.courses.any? %>
    <div class="row">
      <div class="col-sm-12">
        <table class="table">
          <thead>
            <tr>
              <% (1..5).each do |sem| %>
                <th width="20%"><%= "#{sem}º Semestre" %></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr> 
              <% (1..5).each do |sem| %>
                <% @sem = sem %>
                  <td>
                    <% @grad.grad_courses.where(semester: @sem).each do |gc| %>
                      <%= link_to gc.course.name, gc.course, type: "button", class: "label label-info" %></br>
                    <% end %>
                  </td>
              <% end %>
            </tr> 
          </tbody>
        </table>
        <table class="table">
          <thead>
            <tr>
              <% (6..@grad.max).each do |sem| %>
                <th width="20%"><%= "#{sem}º Semestre" %></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr> 
              <% (6..@grad.max).each do |sem| %>
                <% @sem = sem %>
                  <td>
                    <% @grad.grad_courses.where(semester: @sem).each do |gc| %>
                      <%= link_to gc.course.name, gc.course, type: "button", class: "label label-info" %></br>
                    <% end %>
                  </td>
              <% end %>
            </tr> 
          </tbody>
        </table>
      </div>
    </div>

  <% end %>
  
</div>
<%= link_to 'Edit', edit_grad_path(@grad) %> |
<%= link_to 'Back', grads_path %>