config/routes.rb
Rails.application.routes.draw do
  
  resources :grads
  resources :grad_courses, only: [:edit]
  resources :courses
  resources :schools
  post 'grad_courses/:id', to: 'grad_courses#update'
  get 'pages/home', to: 'pages#home'
  root 'pages#home'

end

app/models/school.rb
class School < ActiveRecord::Base
    has_many :courses
    has_many :grads
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :city, :public, :website)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<div class="container well">
  <%= form_for @school, html: {class: "form-horizontal"} do |f| %>
    <% if @school.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>
  
        <ul>
        <% @school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :Nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :Cidade, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :"Pública", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.check_box :public %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :Site, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :website, class: "form-control" %>
      </div>
    </div>
    <div class="actions">
      <div class="form-group">
        <%= f.submit :Salvar, class: "btn btn-default col-sm-2 col-sm-offset-9" %>
      </div>
    </div>
  <% end %>
</div>

app/views/schools/edit.html.erb
<h1>Editar Escola</h1>

<%= render 'form' %>

<%= link_to 'Ver', @school %> |
<%= link_to 'Voltar', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Escolas Cadastradas</h1>

<div class="container well">
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-4">
          Nome
        </th>      
        <th class="col-sm-2">
          Cidade
        </th>      
        <th class="col-sm-1">
          Tipo
        </th>      
        <th class="col-sm-3">
          Site
        </th>
      </tr>
    </thead>
    <tbody>

      <% @schools.each do |school| %>
        <tr>
          <td>
            <%= link_to "#{school.name}", school %>
          </td>      
          <td>
            <%= school.city %>
          </td>      
          <td>
            <% if school.public %>
              Pública
            <% else %>
              Privada
            <% end %>
          </td>      
          <td>
            <%= school.website %>
          </td>
          <td>
            <%= link_to 'Editar', edit_school_path(school), type: "button", class: "label label-primary" %>
            <%= link_to 'Deletar', school, type: "button", class: "label label-danger", method: :delete, data: { confirm: 'Tem certeza?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Nova Escola', new_school_path, type: "button", class: "btn btn-success btn-sm" %>

app/views/schools/new.html.erb
<h1>Nova Escola</h1>

<%= render 'form' %>

<%= link_to 'Voltar', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @school.name %>
  </br>
  <small><%= @school.city %></small>
  <small> | </small>
  <small>
    <% if @school.public %>
      Pública
    <% else %>
      Privada
    <% end %>
  </small>
  <small> | </small>
  <small><%= link_to "#{@school.website}", "#{@school.website}", :target => "_blank" %></small>
</h1>
<div class="container well">
  <div class="row">
    <div class="col-sm-1">
      <strong>Graduações</strong>
    </div>
    <div class="col-sm-11">
      <% if @school.grads.any? %>
        <ul class="list-inline">
          <%= render @school.grads %>
        </ul>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-1">
      <strong>Cursos</strong>
    </div>
    <div class="col-sm-11">
      
      <% if @school.courses.any? %>
        <ul class="list-inline">
          <%= render @school.courses %>
        </ul>
      <% end %>
      
    </div>
  </div>
</div>

<%= link_to 'Editar', edit_school_path(@school) %> |
<%= link_to 'Voltar', schools_path %>