config/routes.rb
Rails.application.routes.draw do
  
  resources :grads
  resources :grad_courses, only: [:edit]
  resources :courses
  resources :schools
  post 'grad_courses/:id', to: 'grad_courses#update'
  get 'pages/home', to: 'pages#home'
  root 'pages#home'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag "LOGO_WIDE.png", id:"logo_img" %>
        <% end %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Faculdades', schools_path %></li>
        <li><%= link_to 'Graduações', grads_path %></li>
        <li><%= link_to 'Cursos', courses_path %></li>
        <li><%= link_to 'Blog', '' %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </div>
          </div>
        </div>
        
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escola Pirata - Redefine Education!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    
    <%= yield %>
  </div>


</body>
</html>